ARIBA run with this command:
/usr/bin/ariba run ariba_database/ ../sample_reads_for_ariba/ERR13299686/ERR13299686_1.fastq ../sample_reads_for_ariba/ERR13299686/ERR13299686_2.fastq ariba_output_run_ERR13299686
from this directory: /home/evannaughton/ChitinVariAriba

ARIBA version: 2.14.6

External dependencies:
bowtie2	2.5.2	/usr/bin/bowtie2
cdhit	4.8.1	/usr/bin/cd-hit-est
nucmer	3.1	/usr/bin/nucmer

External dependencies OK: True

Python version:
3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]

Python packages:
ariba	2.14.6	/usr/lib/python3/dist-packages/ariba/__init__.py
bs4	4.12.3	/usr/lib/python3/dist-packages/bs4/__init__.py
dendropy	4.6.1	/usr/lib/python3/dist-packages/dendropy/__init__.py
pyfastaq	3.17.0	/usr/lib/python3/dist-packages/pyfastaq/__init__.py
pymummer	0.11.0	/usr/lib/python3/dist-packages/pymummer/__init__.py
pysam	0.22.0	/usr/lib/python3/dist-packages/pysam/__init__.py

Python packages OK: True

Everything looks OK: True
